from enum import Enum

# Order is in alphabetical according to the full team name and not the abbreviation
class TeamName(str, Enum):
    ANA = "ANA"
    ARI = "ARI"
    BOS = "BOS"
    BUF = "BUF"
    CGY = "CGY"
    CAR = "CAR"
    CHI = "CHI"
    COL = "COL"
    CBJ = "CBJ"
    DAL = "DAL"
    DET = "DET"
    EDM = "EDM"
    FLA = "FLA"
    LAK = "LAK"
    MIN = "MIN"
    MTL = "MTL"
    NSH = "NSH"
    NJD = "NJD"
    NYI = "NYI"
    NYR = "NYR"
    OTT = "OTT"
    PHI = "PHI"
    PIT = "PIT"
    SJS = "SJS"
    STL = "STL"
    TBL = "TBL"
    TOR = "TOR"
    VAN = "VAN"
    WAS = "WAS"
    WPJ = "WPJ"
    SEA = "SEA"
